---
- name: Cilium | Add cilium helm repository
  community.kubernetes.helm_repository:
    name: cilium
    repo_url: "{{ cilium_helm_repo }}"
  when: inventory_hostname == groups['kube_controllers'][0]

# - name: Cilium | Install cilium helm chart
#   ansible.builtin.command: >
#     helm install cilium cilium/cilium --version {{ cilium_version }}
#       --namespace kube-system
#       --set kubeProxyReplacement=strict
#       --set k8sServiceHost={{ kube_apiserver_advertise_address }}
#       --set k8sServicePort={{ kube_apiserver_bind_port }}
#   when: inventory_hostname == groups['kube_controllers'][0]

- name: Cilium | Install cilium helm chart
  community.kubernetes.helm:
    release_name: cilium
    release_namespace: kube-system
    chart_ref: "cilium/cilium"
    chart_version: "{{ cilium_version }}"
    release_values: "{{ lookup('template', 'cilium_values.yml.j2') | from_yaml }}"
  when: inventory_hostname == groups['kube_controllers'][0]
...
