---
- name: Main | import common tasks
  ansible.builtin.import_tasks: "common.yml"

- name: Main | include os specific tasks
  ansible.builtin.include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."

- name: Main | check kubernetes cluster is already setup
  ansible.builtin.file:
    path: "/etc/kubernetes/manifests/kube-apiserver.yaml"
    state: absent
  check_mode: true
  register: is_k8s
  become: true
  delegate_to: "{{ groups['kube_controllers'][0] }}"
  run_once: true

- name: Main | import cluster tasks
  ansible.builtin.import_tasks: "cluster.yml"
  when: not is_k8s.changed

- name: Main | import setup tasks
  ansible.builtin.import_tasks: "setup.yml"
...
