---
- name: k8s | systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  register: reload_systemd_daemon
  failed_when: reload_systemd_daemon.failed

- name: k8s | systemctl restart kubelet.service
  ansible.builtin.service:
    name: "kubelet.service"
    state: "restarted"
    enabled: true
  become: true
  register: restart_kubelet_service
  failed_when: restart_kubelet_service.failed
...
